//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MooN.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MooNTYPE                    130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DLG_CINFIG                  310
#define IDD_FORMLISTVIEW                311
#define IDR_MENU1                       312
#define IDR_MAINMENU                    312
#define IDD_FROMPROPERTIES              313
#define IDR_MENU_OCR                    316
#define IDC_EDIT_SRCPATH                1000
#define IDC_EDIT2                       1001
#define IDC_EDIT_LOGPATH                1001
#define IDC_EDIT_FILENAME               1001
#define IDC_BUTTON1                     1002
#define IDC_BUTTON_BROWSER              1002
#define IDC_BN_ENG_FONT                 1002
#define IDC_BN_DESKEW_ALL               1002
#define IDC_LIST1                       1003
#define IDC_BN_CHI_FONT                 1003
#define IDC_CHECK_AUTOFILL              1004
#define IDC_BN_KOR_FONT                 1004
#define IDC_SLIDER1                     1005
#define IDC_MFCCOLORBUTTON1             1006
#define IDC_EDIT1                       1007
#define IDC_CHECK_ENG                   1008
#define IDC_CHECK_CHI                   1009
#define IDC_CHECK_KOR                   1010
#define IDC_RADIO_HORIZON               1011
#define IDC_RADIO_VERT                  1012
#define IDC_EDIT_ENG_SIZE               1013
#define IDC_EDIT_KOR_SIZE               1014
#define IDC_EDIT_CHI_SIZE               1015
#define IDC_EDIT6                       1016
#define IDC_EDIT_DESKEW                 1016
#define IDC_BUTTON4                     1017
#define IDC_BN_APP_DESKEW               1017
#define IDC_BUTTON5                     1018
#define IDC_BN_CANCEL                   1018
#define IDC_BUTTON6                     1019
#define IDC_BN_DEL_PARA                 1019
#define IDC_BUTTON7                     1020
#define IDC_BN_ADD_PARA                 1020
#define IDC_BUTTON8                     1021
#define IDC_BN_RE_EXTRACT               1021
#define IDC_BN_EXTRACTLINE              1022
#define IDC_EDIT_ENCODE                 1023
#define IDC_COMBO_LANG                  1024
#define IDC_BN_DEL_ALLLINBES            1025
#define IDC_EDIT_CONFIDENCE             1026
#define IDC_BN_ADD_MODIFYOCRRES         1027
#define IDC_BN_DEL_OCRRES               1028
#define IDC_EDIT3                       1029
#define IDC_EDIT_KEYWORD_SEARCH         1029
#define IDC_BN_KEYWORD_SEARCH           1030
#define IDC_BN_RUNOCR                   1031
#define IDC_CHECK_LINEBIOX              1032
#define IDC_BN_WORD_CONFIRM             1033
#define IDC_BN_ADD_OCRRES               1034
#define IDC_SLIDER_CONFI                1035
#define IDC_BN_ALL_DEL_OCRRES           1036
#define IDC_EDIT_CONFI                  1037
#define IDC_BN_ENCODE                   1038
#define ID_FILE_EXIT                    32771
#define ID_VIEW_INITIALIZE              32772
#define ID_PROJECT_ADDIMAGE             32773
#define ID_PROJECT_REMOVEIMAGE          32774
#define ID_TOOLS_CUTAREA                32775
#define ID_TOOLS_SEARCH                 32776
#define ID_TOOLS_KEYWORDSEARCH          32777
#define ID_TOOLS_CLEARRESULT            32778
#define ID_ANALYZE_EXTRACTTEXTBOUNDARY  32779
#define ID_HELP_ABOUT                   32780
#define ID_FILE_OPENFILE                32781
#define ID_PROJECT_CONFIGURATION        32782
#define ID_VIEW_LOGVIEW                 32783
#define ID_VIEW_LISTVIEW                32784
#define ID_OCR_RECOGNIZEENGLISHWORD     32784
#define ID_OCR_RECOGNIZEENGLISHCHARACTER 32785
#define ID_OCR_SEARCH                   32786
#define ID_OCR_ENGLISHWORD              32787
#define ID_OCR_ENGLISHCHARACTER         32788
#define ID_OCR_CHINISEWORD              32789
#define ID_OCR_CHINESECHARACTER         32790
#define ID_OCR_KOREANWORD               32791
#define ID_OCR_KOREANCHARACTER          32792
#define ID_OCR_CHINESEWORD              32793
#define ID_OCR_ENGLISHCHARACTER32794    32794
#define ID_OCR_KOREANWORD32795          32795
#define ID_OCR_KOREANWO                 32796
#define ID_ANALYSIS_DATATRAINING        32797
#define ID_OCR_REMOVENOISE              32798
#define ID_FILE_EXPORTDATABASE          32799
#define ID_OCR_CHARACTERRECOGNITION     32800
#define ID_CHARACTERRECOGNITION_ENGLISH 32801
#define ID_ENGLISH_WORD                 32802
#define ID_ENGLISH_CHARACTER            32803
#define ID_CHARACTERRECOGNITION_CHINESE 32804
#define ID_CHINESE_WORD                 32805
#define ID_CHINESE_CHARACTER            32806
#define ID_CHARACTERRECOGNITION_KOREAN  32807
#define ID_KOREAN_WORD                  32808
#define ID_KOREAN_CHARACTER             32809
#define ID_OCR_ENGLISHCHARACTE          32810
#define ID_OCR_SEARCH32811              32811
#define ID_OCR_SEARCH_SELECTION         32812
#define ID_OCR_ADDTEXTBOX               32813
#define ID_OCR_DELETETEXTBOX            32814
#define ID_TEXTBOX_ADD                  32815
#define ID_TEXTBOX_DELETE               32816
#define ID_LINEBOX_ADD                  32817
#define ID_LINEBOX_DELETE               32818
#define ID_OCR_DELETELINEBOX            32819
#define ID_OCR_DELETETEXTBOX32820       32820
#define ID_OCR_ROTATELINE               32821
#define ID_OCR_SPLITELINE               32822
#define ID_OCR_TRAINTEXT                32823
#define ID_OCR_ADD_LINEBOX              32824
#define ID_OCR_DELETEL_INEBOX           32825
#define ID_OCR_ROTATE_LINE              32826
#define ID_OCR_SPLITE_LINE              32827
#define ID_OCR_ADD_TEXTBOX              32828
#define ID_OCR_DELETETE_XTBOX32820      32829
#define ID_OCR_TRAIN_TEXT               32830
#define ID_OCR_UNDOROTAION              32831
#define ID_OCR_UNDOROTAION_LINE         32832
#define ID_RECOGNIZETEXT_FROMUSERDB     32833

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        317
#define _APS_NEXT_COMMAND_VALUE         32834
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           314
#endif
#endif
